# Site settings
title: pdxbyte
subtitle: Portland Byte
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://pdxbyte.org" # the base hostname & protocol for your site

# Build settings
markdown: kramdown

